MvcOnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int Departmanid { get; set; }

        //kısaltma(uzunluk) ve degisken tipi
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }

        public bool Durum { get; set; } 

        //iliskiler
        public ICollection<Personel> Personels { get; set; }    
    }
}

MvcOnlineTicariOtomasyon/Controllers/DepartmanController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;


namespace MvcOnlineTicariOtomasyon.Controllers
{
    [Authorize]
    public class DepartmanController : Controller
    {
        // GET: Departman
        Models.Siniflar.Context c = new Models.Siniflar.Context();
        
        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }

        [Authorize(Roles ="A")]
        [HttpGet]
       
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        
        public ActionResult DepartmanEkle(Departman D)
        {
            c.Departmans.Add(D);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanSil(int id)
        {
            var deger = c.Departmans.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetir(int id)
        {
            var degerler = c.Departmans.Find(id);
            return View(degerler);
        }

        public ActionResult DepartmanGuncelle(Departman D)
        {
            var degerler = c.Departmans.Find(D.Departmanid);
            degerler.DepartmanAd = D.DepartmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();
            //Departman Adını Çekip viewbag ile gönderme
            //1.yol
            var deger = c.Departmans.Find(id).DepartmanAd;
            //2.yol
            //var deger = c.Departmans.Where(x => x.Departmanid == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.dgr = deger;
            return View(degerler);
        }

        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var deger = c.Personels.Where(x => x.Personelid == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            ViewBag.dgr = deger;
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2 style="text-align:center;">Departman Detayları</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-size:18px; ">Departman Adı: @ViewBag.dgr</li>
</ol>

<table class="table table-hover">
    <thead>
        <tr>
 
            <th>Ad</th>
            <th>Soyad</th>
            <th>Görsel</th>
            <th>Satışlar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
              
                <td>@item.PersonelAd</td>
                <td>@item.PersonelSoyad</td>
                <td><img src="@item.PersonelGorsel" width="60" /></td>
                <td><a style="background-color:coral" class="btn btn-default" href="/Departman/DepartmanPersonelSatis/@item.Personelid">Satışlar</a></td>
            </tr>
        }



    </tbody>
</table>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Departman Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Departman Adı")
    @Html.TextBoxFor(x =>x.DepartmanAd, new { @class = "form-control", Style = "width:50%;" })

    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Departman Güncelle</h2>
<br />

@using (Html.BeginForm("DepartmanGuncelle","Departman",FormMethod.Post, new {@class="form-group"}))
            {
                @Html.HiddenFor(x=>x.Departmanid)
                @Html.Label("Departman Adı")
                @Html.TextBoxFor(x=>x.DepartmanAd, new  {@class="form-control", style="width:30%;"})
                <br />
                <button class="btn btn-warning">Güncelle</button>
                
            }

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Personel Satış Hareketleri</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-size:18px; ">Personel Adı: @ViewBag.dgr</li>
</ol>

<table class="table table-condensed">
    <thead>
        <tr>
         
            <th>Ürün</th>
            <th>Müşteri</th>
            <th>Personel</th>
            <th>Tarih</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Yazdır</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
      
                <td>@item.Urun.UrunAd</td>
                <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
                <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
                <td>@Convert.ToDateTime(@item.Tarih).ToString("dd/mm/yyyy")</td>
                <td>@item.Adet</td>
                <td>@item.Fiyat</td>
                <td>@item.ToplamTutar</td>
                <td><a class="btn btn-default" style="background-color:darkcyan; color:white;">Yazdır</a></td>
            </tr>
        }



    </tbody>
</table>

MvcOnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar;
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    th, td {
        text-align: center;
    }
</style>
<br />
<h2 style="text-align:center;">Departmanlar</h2>
<br />
<table class="table table-bordered" style="margin-top:20px;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Kategori Ad</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Departman Detay</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Departmanid</td>
                <td>@item.DepartmanAd</td>
                <td><a href="/Departman/DepartmanSil/@item.Departmanid" class="btn btn-danger">Sil</a></td>
                <td><a href="/Departman/DepartmanGetir/@item.Departmanid" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/Departman/DepartmanDetay/@item.Departmanid" class="btn btn-default" style="background-color:lightcoral; color:white;">Detaylar</a></td>

            </tr>
        }


    </tbody>
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-info">Yeni Departman Ekle</a>