MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var satis = c.SatisHarekets.ToList();
            return View(satis);
        }

        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd+" "+x.PersonelSoyad,
                                               Value = x.Personelid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.Urunid.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            List<SelectListItem> deger3 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd +" "+ x.CariSoyad,
                                               Value = x.Cariid.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;


            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket S)
        {
            c.SatisHarekets.Add(S);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.Personelid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.Urunid.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            List<SelectListItem> deger3 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.Cariid.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;

            var deger = c.SatisHarekets.Find(id);
            return View(deger);
        }

        public ActionResult SatisGuncelle(SatisHareket satis)
        {
            var sat = c.SatisHarekets.Find(satis.Satisid);
            sat.Fiyat=satis.Fiyat;  
            sat.Tarih=satis.Tarih;  
            sat.Cariid=satis.Cariid;  
            sat.Adet=satis.Adet;  
            sat.Urunid=satis.Urunid;
            sat.Personelid = satis.Personelid;
            sat.ToplamTutar = satis.ToplamTutar;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var deger = c.SatisHarekets.Where(x => x.Satisid == id).ToList();
            return View(deger);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    th, td {
        text-align: center;
    }
</style>
<br />
<h2 style="text-align:center;">Satışlar</h2>
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Müşteri</th>
            <th>Personel</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>Güncelleme</th>
            <th>Sil</th>
            <th>Detaylar</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Satisid</td>
                <td>@item.Urun.UrunAd</td>
                <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
                <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
                <td>@item.Fiyat</td>
                <td>@item.Adet</td>
                <td>@item.ToplamTutar</td>
                <td>@item.Tarih</td>
                <td><a href="/Satis/SatisGetir/@item.Satisid" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/Satis/SatisSil/@item.Satisid" class="btn btn-danger">Sil</a></td>
                <td><a href="/Satis/SatisDetay/@item.Satisid" class="btn btn-default" style="background-color:lightcoral; color:white;">Detaylar</a></td>
            </tr>
        }


    </tbody>
</table>
<a href="/Satis/YeniSatis" class="btn btn-info">Satış Yap</a>


<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl1').dataTable({
        "language" : {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Satış Detayı</h2>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Müşteri</th>
            <th>Personel</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>Yazdır</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Satisid</td>
                <td>@item.Urun.UrunAd</td>
                <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
                <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
                <td>@item.Fiyat</td>
                <td>@item.Adet</td>
                <td>@item.ToplamTutar</td>
                <td>@item.Tarih</td>
                <td><a style="background-color:coral" class="btn btn-default" href="/Departman/DepartmanPersonelSatis/@item.Personelid">Yazdır</a></td>
            </tr>
        }



    </tbody>
</table>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style=" text-align:center;">Satış Güncelleme</h2>

<br />
@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post, new { @class = "form-group" }))
{
    @Html.HiddenFor(z=>z.Satisid)
    @Html.Label("Ürün Adı")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr2, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Müşteri Ad-Soyad")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr3, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Personel Ad-Soyad")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr1, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Adet")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Toplam Tutar")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control", style = "width:30%;" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Satış Yapma</h2>

<form class="form-group" method="post">
    @Html.Label("Ürün Adı")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr2, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Müşteri Ad-Soyad")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr3, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Personel Ad-Soyad")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr1, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control", style = "width:30%;" })*@
    <br />
    @Html.Label("Adet")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Fiyat")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Toplam Tutar")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control", style = "width:30%;" })
    <br />
    <button class="btn btn-primary">Satış</button>


</form>