MvcOnlineTicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(300)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }


    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Context c = new Context();
        public ActionResult Index(string p)
        {
            var kargo = c.KargoDetays.ToList();
            if (!string.IsNullOrEmpty(p))
            {
                kargo = kargo.Where(x => x.TakipKodu.Contains(p)).ToList();

            }

           
            return View(kargo);
        }

        [HttpGet]
        public ActionResult YeniKargo()
        {
            Random rnd = new Random();
            string[] Karakterler = { "A", "B", "C", "D" };
            int k1, k2, k3;
            k1=rnd.Next(0,4);
            k2=rnd.Next(0,4);
            k3=rnd.Next(0,4);
            int s1, s2, s3;
            s1=rnd.Next(100,1000);
            s2=rnd.Next(10,99);
            s3=rnd.Next(10,99);
            string kod = s1.ToString() + Karakterler[k1] + s2 + Karakterler[k2] + s3 + Karakterler[k3];
            ViewBag.takipkod = kod;
            return View();
        }

        [HttpPost]
        public ActionResult YeniKargo(KargoDetay k)
        {
            c.KargoDetays.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KargoTakip(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar;
@model List<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



<style>
    th, td {
        text-align: center;
    }
</style>
<br />
<h2 style="text-align:center;">Kargolar</h2>
<br />
@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>
        <label>Kargo Takip No:</label> @Html.TextBox("p")
        <input type="submit" value="Ara" class="btn btn-primary" />
    </p>
}
<table class="table table-bordered" style="margin-top:20px;">
    <thead>
        <tr>

            <th>Takip No</th>
            <th>Personel</th>
            <th>Alıcı</th>
            <th>Tarih</th>
            <th>Detaylar</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.TakipKodu</td>
                <td>@item.Personel</td>
                <td>@item.Alici</td>
                <td>@item.Tarih</td>
                <td><a href="/Kargo/KargoTakip/@item.TakipKodu" class="btn btn-default" style="background-color:lightcoral; color:white;">Detaylar</a></td>

            </tr>
        }


    </tbody>
</table>
<a href="/Kargo/YeniKargo" class="btn btn-info">Yeni Kargo Girişi</a>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Kargo Takip Ekranı</h2>
<br />


<table class="table table-striped">
    <thead>
        <tr>
            <th>Açıklama</th>
            <th>Tarih</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Aciklama</td>
                <td>@item.TarihZaman</td>
            </tr>
        }
    </tbody>
</table>

MvcOnlineTicariOtomasyon/Views/Kargo/YeniKargo.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.KargoDetay
@{
    ViewBag.Title = "YeniKargo";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Kargo Ekle</h2>
<br />
<form method="post" class="form-group">
    @Html.Label("Takip Kodu")
   
    <input type="text" class="form-control" name="TakipKodu" style="width:30%;" value="@ViewBag.takipkod" readonly/>
    <br />
    @Html.Label("Personel")
    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Alıcı")
    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Tarih")
    <input type="date" class="form-control" name="Tarih" style="width:30%;" />
    <br />
    <button class="btn btn-outline-primary">Ekle</button>
</form>