MvcOnlineTicariOtomasyon/Models/Siniflar/Urun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Urun
    {
        [Key]
        public int Urunid { get; set; }

        //kısaltma(uzunluk) ve degisken tipi
        [Column(TypeName ="Varchar")]
        [StringLength(30)]
        public string UrunAd { get; set; }

        //kısaltma(uzunluk) ve degisken tipi
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Marka { get; set; }
        public short Stok { get; set; }
        public decimal AlisFiyat { get; set; }
        public decimal SatisFiyat { get; set; }
        public bool Durum { get; set; }
        public int Kategoriid { get; set; } 

        //kısaltma(uzunluk) ve degisken tipi
        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string UrunGorsel { get; set; }

        //iliskiler
        public ICollection<SatisHareket> SatisHarekets { get; set; }
        public virtual Kategori Kategori { get; set; }
         
    }
}

MvcOnlineTicariOtomasyon/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        Context c = new Context();
        public ActionResult Index(string p)
        {
            var urunler = c.Uruns.Where(x => x.Durum == true).ToList();
            if (!string.IsNullOrEmpty(p))
            {
                urunler = urunler.Where(x => x.UrunAd.Contains(p)).ToList();
               
            }
           
             return View(urunler);
            
            
        }

        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrun(Urun U)
        {
            c.Uruns.Add(U);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunSil(int id)
        {
            var deger = c.Uruns.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

    
        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            var degerler = c.Uruns.Find(id);
            return View("UrunGetir",degerler);
        }

     
        public ActionResult UrunGuncelle(Urun U)
        {
            var deger = c.Uruns.Find(U.Urunid);
            deger.UrunAd = U.UrunAd;
            deger.Marka=U.Marka;    
            deger.Stok=U.Stok;  
            deger.AlisFiyat=U.AlisFiyat;
            deger.SatisFiyat = U.SatisFiyat;
            deger.Durum=U.Durum;
            deger.UrunGorsel=U.UrunGorsel;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunListesi()
        {
            var degerler = c.Uruns.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult SatisYap(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.Personelid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var deger2 = c.Uruns.Find(id);
            ViewBag.dgr2 = deger2.Urunid;
            ViewBag.dgr3 = deger2.SatisFiyat;
            return View();  
        }
        [HttpPost]
        public ActionResult SatisYap(SatisHareket p)
        {
            p.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index","Satis");
        }



    }
}

MvcOnlineTicariOtomasyon/Views/Urun/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Urun>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    th, td {
        text-align: center;
    }
</style>
<br />
<h2 style="text-align:center;">Ürünler</h2>
<br />
@using(Html.BeginForm("Index","Urun",FormMethod.Get))
            {
                <p>
                    <label>Ürün Adı:</label> @Html.TextBox("p")
                    <input  type="submit" value="Ara" class="btn btn-primary"/>
                </p>
            }
<table class="table table-bordered" style="margin-top:20px;">
    <thead>
        <tr>
       
            <th>Ürün Ad</th>
            <th>Kategori</th>
            <th>Marka</th>
            <th>Stok</th>
            <th>Aliş Fiyat</th>
            <th>Satış Fiyat</th>
            <th>Ürün Resmi</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Satış Yap</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
               
                <td>@item.UrunAd</td>
                <td>@item.Kategori.KategoriAd</td>
                <td>@item.Marka</td>
                <td>@item.Stok</td>
                <td>@item.AlisFiyat ₺</td>
                <td>@item.SatisFiyat ₺</td>
          
                <td><img src="@item.UrunGorsel" width="80px" /></td>
                <td><a href="/Urun/UrunSil/@item.Urunid" class="btn btn-danger">Sil</a></td>
                <td><a href="/Urun/UrunGetir/@item.Urunid" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/Urun/SatisYap/@item.Urunid" class="btn btn-outline-primary">Satış</a></td>

            </tr>
        }


    </tbody>
</table>
<a href="/Urun/YeniUrun" class="btn btn-primary">Yeni Ürün Ekle</a>

MvcOnlineTicariOtomasyon/Views/Urun/SatisYap.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisYap";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<br />
<h2 style="">Satış Yap</h2>
<br />
<form class="form-group" method="post">

    @Html.Label("Ürün ID")
    <input type="text" name="Urunid" value="@ViewBag.dgr2" class="form-control" style="width:30%;" readonly />
    <br />
    @Html.Label("Personel Ad-Soyad")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr1, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Müsteri ID")
    @Html.TextBoxFor(x => x.Cariid, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Adet")
    <input name="Adet" type="number" class="form-control" min="0" placeholder="Adet Girniz..." id="txt1" onchange="sum();" style="width:30%;" />
    <br />
    @Html.Label("Fiyat")
    <input type="text" name="Fiyat" value="@Convert.ToInt64(ViewBag.dgr3)" class="form-control" style="width:30%;" id="txt2" onkeyup="sum();" />
    <br />
    @Html.Label("Toplam Tutar")
    <input type="text" name="ToplamTutar" id="txt3" class = "form-control", style = "width:30%;" />
    <br />

    <button class="btn btn-primary">Staış Yap</button>

</form>

@*<input type="text" id="txt1" onkeyup="sum()"/>*@



<script>
    function sum() {
        var sayi1 = Number(document.getElementById("txt1").value);
        var sayi2 = Number(document.getElementById("txt2").value);
        var sonuc = sayi1 * sayi2;
        if (!isNaN(parseInt(sonuc))) {

            document.getElementById('txt3').value = Number(sonuc);

        }
    }
</script>

MvcOnlineTicariOtomasyon/Views/Urun/UrunGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Ürün Güncelleme</h2>
<br />
@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post, new { @class = "form-group" }))
{
    @Html.HiddenFor(x => x.Urunid);

    @Html.Label("Ürün Adı")
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, "Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Marka")
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Stok")
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Alış Fiyatı")
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Satış Fiyatı")
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Durum")
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Ürün Görsel")
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control", style = "width:30%;" })
    <br />
    <button class="btn btn-warning">Ürünü Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Urun/UrunListesi.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar

@model List<Urun>

@{

    Layout = null;

}

<br />

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Ürün Id</th>

                <th>Adı</th>

                <th>Marka</th>

                <th>Stok</th>

                <th>Alış Fiyat</th>

                <th>Satış Fiyat</th>

                <th>Durum</th>

                <th>Kategori</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.Urunid</td>

                    <td>@x.UrunAd</td>

                    <td>@x.Marka</td>

                    <td>@x.Stok</td>

                    <td>@x.AlisFiyat</td>

                    <td>@x.SatisFiyat</td>

                    <td>@x.Durum</td>

                    <td>@x.Kategori.KategoriAd</td>

                </tr>

            }



        </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

$(document).ready(function() {

    var table = $('#example').DataTable( {

        lengthChange: false,

        buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]

    } );



    table.buttons().container()

        .appendTo( '#example_wrapper .col-md-6:eq(0)' );

} );

    </script>

</body>

</html>

MvcOnlineTicariOtomasyon/Views/Urun/YeniUrun.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="text-align:center;">Yeni Ürün Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Ürün Adı")
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x=>x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1,"Seçiniz..", new { @class = "form-control", style = "width:30%;" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control", style = "width:30%;" })*@
    <br />
    @Html.Label("Marka")
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Stok")
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Alış Fiyatı")
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Satış Fiyatı")
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Durum")
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control", style = "width:30%;" })
    <br />
    @Html.Label("Ürün Görsel")
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control", style = "width:30%;" })
    <br />
    <button class="btn btn-primary">Ürünü Ekle</button>

</form>